### ISSUE TITLE
Redmineサーバのデータ移設

### ISSUE THREAD

**Issue by sperkbird** [histudy/infra-replace#4]
既存RedmineサーバからDB、ファイルのデータを移設する

#3 完了後に実施

## 対応事項
* 整合性確保のため、既存サーバの更新停止期間を決定する
* 利用者向けに既存サーバの更新停止期間を告知
* 既存サーバからのDB、ファイルデータを確保
* 新サーバへのデータインポート、マイグレーション処理を実施
* 各種データの整合性確認
* 利用者向けにRedmine基盤切り替えを広報

**Comment by wate** [comment]
@sperkbird Redmineのマイグレーション(アップグレード)に関するドキュメントは以下の通りです。

https://www.redmine.org/projects/redmine/wiki/RedmineUpgrade

**Comment by wate** [comment]
@sperkbird 

既存サーバーからのデータ移行に関しては、大まかに以下のように考えています。
※個人でもRedmineを利用しているため現状では既存サーバーはそのまま残す感じになると思います。

### データ移行の検証

1. 既存サーバーのRedmineデータをバックアップ
2. 新サーバーにバックアップデータをrsyncで転送
3. 新サーバー側インポートおよびマイグレーションを実行
4. 整合性確認

### データ移行当日

#### 既存サーバー(個人サーバー)

1. 既存サーバーのRedmineデータをバックアップ
2. 新サーバーにバックアップデータをrsyncで転送
3. 勉強会のプロジェクトをロック
    * この段階で勉強会のプロジェクトはロックされデータは変わらなくなる
    * 誤って旧サーバーにログインしてしまっても、ロックされているため編集出来ない

#### 新サーバー

1. 新サーバー側インポートおよびマイグレーションを実行
2. 整合性確認
3. Redmine上の不要なデータを削除
    * 個人サーバー内の別プロジェクトの情報などが残っているため

### 備考

既存サーバー側で先にプロジェクトをロックし、データを編集できなくした上で
新サーバー側でロックを解除するという順序でもデータの整合性は維持できると思います。

**Comment by wate** [comment]
@sperkbird @fu7mu4  @nogajun @akiya64 

既存Redmineからのデータの移行ですが、 @sperkbird くんの負荷が大きいため、
未完了のチケットおよび各種ファイルを手動で移すことにし、
まずはRedmineサーバーの移行を最優先すると言う話で落ちつきました。
