### ISSUE TITLE
Webサイトのnpmパッケージアップデート

### ISSUE THREAD

**Issue by sperkbird** [histudy/infra-replace#6]
Webサイトの生成用に利用しているhexoの前提パッケージ群が古くなっており
セキュリティの指摘がGithubのBotより発生している

## 対応事項
* BotからのPull requestのマージ
* 生成処理への影響確認
* masterブランチへの反映

**Comment by akiya64** [comment]
Hexo は検討で触った程度ですが、私にアサインしていただいても構いません。
Hugo で簡単なサイトは作ったことがあるので多分いけるかと。

**Comment by wate** [comment]
そうですね、もともとhexoのnpmパッケージ周りでセキュリティ警告が出始め、
もうHugoでいいんじゃね?って感じで話が出てたので、
静的サイトジェネレーターをHugoに替えてしまえばいいかなと

既に以下のようなテーマもそろってるので
https://jamstackthemes.dev/theme/

**Comment by sperkbird** [comment]
Hugoだとシングルバイナリなので今回みたいな脆弱性対応も簡単そうですね
記事のYAMLの互換性あたりで多少変換は必要かもしれませんが、この機会に移行してしまっても良いと思います

リポジトリはどうしましょうか？
既存のhistudy/siteに対して移行用ブランチを切って最終的にPull requestする感じで良いでしょうか？
（もしくは別リポジトリで作業していくか）

**Comment by wate** [comment]
@sperkbird そうですね、とりあえずは現在のリポジトリに移行用のブランチを切ってHugoに対応、
確認が取れたらマージってのが一番スムーズかなと

**Comment by wate** [comment]
@sperkbird 

現在のwebサイト用のリポジトリに以下のデプロイ処理も残ってるので、
それがそのまま使える形が理想的かなと

https://github.com/histudy/site/blob/master/deploy.sh

ただ、今回のサーバー更改の時にデプロイ専用のアカウントは別途用意するようにした方がいいかもしれません。
※CircleCI等のCIサービス使ってここら辺も自動化したいですが、今回のサーバー更改とは要件が異なるため、
サーバー更改後に別のissueを立てるようにします。

**Comment by sperkbird** [comment]
では方針として、下記で進めましょうか。
* Hexo -> HugoにSSGを切り替え
* Hexoのnpm脆弱性対応としては対応無しとして本issueはClose
* 切り替え対応はhistudy/site側のissueとして新規作成
* Hugoのテーマは切り替え対応本体とは別issueで議論、決定

@akiya64 histudy/site側のissueにアサインさせて頂いてもよろしいでしょうか？

**Comment by akiya64** [comment]
@sperkbird 
はい、histudy/site の方にアサインしていただけますか。

**Comment by sperkbird** [comment]
@akiya64 ありがとうございます。
ただ、histudy/site側でコミットなどでコントリビューター扱いになっていないとIssueにアサインが出来ないようです。

お手数ですが、siteリポジトリにIssue作成していますので、コメント追加をお願いできますでしょうか。

**Comment by sperkbird** [comment]
方針決定し、histudy/site側でIssue立ち上げたのでこちらはCloseします
