### ISSUE TITLE
WebサイトのSSG変更時にCicleCIのテストするための検証サーバがほしい

### ISSUE THREAD

**Issue by sperkbird** [histudy/infra-replace#8]
histudy/siteのdeploy.shを改修するにあたり、実際にデプロイできるサーバが本番系しかない
大規模のコンテンツ差し替えなどの事前確認用に領域がほしい

**Comment by wate** [comment]
@sperkbird @akiya64 

検証用サーバーの管理の件で、以下のような管理方法を考えてみました。

運用中のサーバーを管理しているリポジトリは別に、検証サーバー用のリポジトリを作成し、
そのリポジトリで検証用サーバーリソースの管理を行う。

管理方法としていくつか方法が考えられるが、
必ずしもtarraformの設定が書ける人ばかりでは無いため、
加古川インフラのメンバーで検証用サーバーのリソースを管理する方が望ましいと思われる。

### 検証サーバー作成から破棄までの流れ

現時点では、Redmineを併用し、加古川インフラのメンバー以外の人も、
Redmine上から検証用サーバーの利用状況が確認出来るようにすることを想定しています。

1. 検証サーバー作成依頼のチケットを登録し、加古川インフラのメンバーの誰かを担当者に設定しアサインする
     * チケット登録時に必要なサーバースペックなどの情報は記載しておく
2. アサインされた担当者は該当リポジトリのコードを修正し、検証用サーバーを作成する
     * 作業を行う場合はステータスを「処理中」に変更し、対応を行っていることが他の人にわかるようにする
     * 検証用サーバーの作成が完了し、確認中の場合はステータスを「処理済み」に変更する 
3. ステータスを「確認待ち」、担当者を「登録者した人」に設定し、チケットを振り替え、接続確認を依頼する
4. 検証サーバーの利用者は、接続確認が取れたら、ステータスを「経過観察中」に変更し、
    検証用サーバーの利用期限として「期日」を設定する
5. 検証作業が完了したら、ステータスを「確認待ち」に変更し、加古川インフラのメンバーを再度チケットを振り返る
6. アサインされた担当者はチケットの内容を確認し、検証サーバー破棄するようにコードを修正し適用を行う(サーバーを破棄する)
     * 対応を行う場合はステータスを「処理中」に変更してから対応を開始する
7. 検証サーバーの破棄が確認できたら、チケットをクローズさせる

### 検証用サーバーの利用状況の確認

ステータスが「経過観察中」になっており、期日到来したチケットが無いか確認を行う。
期日が到来しているチケットに関しては、検証用サーバーの要/不要をチケットの担当者に確認する

#### 「必要」と回答があった場合

検証サーバーを利用している担当者が期日を変更し、検証用サーバーの利用期限を延長する

#### 「不要」と回答があった、または、数日経っても未回答がない場合：

検証サーバーを破棄する

### 懸念事項

必ずしも加古川インフラのメンバーがすぐに動けるとは限らないため、
そうなった場合でも代わりに対応できる人を決めておく必要有り。

また、対応を行う場合は、チケットの担当者を必ず対応を行う人に変更し、
誰が対応を行っている/行ったかをRedmineで追えるようにしておく必要あり

**Comment by wate** [comment]
### その他

加古川インフラのメンバーが毎回対応を対応を行わないといけないため、
ある程度、運用に乗り出した段階で、
段階的に検証用サーバーを自分で作成できる人を増やしていくことを想定しています

- さくらのクラウド上にユーザーを追加する
- 直接terraformのコードの編集権限できるようにする

**Comment by akiya64** [comment]
来週は祝日もあって時間取れそうなので、作業量がそれほどでなければやってみようかと。

リニューアルサイトの表示確認とCIの動作確認のために作って、誰かレビューというか問題ないのが確認できてプロダクションへ反映できたら消去する。

テラフォームはズブの素人です、AnsibleはSSH接続して行う簡単な作業に使い始めたところです。

**Comment by akiya64** [comment]
さくらのクラウドで、Akiyaのユーザーを追加してもらったのでterraformで立ててみます。

**Comment by akiya64** [comment]
できました、SSLとかないんですけど。  
http://test.histudy.jp/

今回は私が単発で使うだけなので、一通りレビューいただいて CI の設定ができたら破棄します。  

この先、勉強会で使う用でサーバー立てて欲しいとかあったら、上記のように Redmine のチケットベースで管理がよいかと思います。
